### PR TITLE
#7 Task. AlexErm

### PR DESCRIPTION
**Pull request by alexErm0**
https://travis-ci.com/github/alexErm0/js-assignments/builds/176722975

### CODE REVIEW

**Comment by AlexMokin** [comment]
indentations are still not consistent, there are missing brackets and semicolon.

Merge the latests changes from master

I'll mark the PR as "Draft", please click "ready for review" when it will be finished. Thank you!

**Comment by AlexMokin** [comment]
there are missing brackets and semicolons, find this mistakes and fix them. Also double check indentations. Do it for all PRs

Please do not re-open until fixed

I'll mark the PR as "Draft", please click "ready for review" when it will be finished. Thank you!

**Comment by alexErm0** [comment]
I've put braces, spaces and semicolons everywhere it can possible be. If there are still some mistakes in indetations please tell me.

**Comment by AlexMokin** [comment]
accepted

**Pull request closed without merging**
