### PR TITLE
#8Task. Dzmitry Bryt

### PR DESCRIPTION
**Pull request by Daqueze21**
https://travis-ci.org/github/Daqueze21/js-assignments/builds/715473758

### CODE REVIEW

**Comment by FedorovD** [comment]
Please clear PR code not related to Task#8 and click "ready for review" when it will be finished. Thank you!

**Comment by FedorovD** [comment]
Remove these changes from Task1-4, there should only be a task#8

**Comment by Daqueze21** [comment]
> Remove these changes from Task1-4, there should only be a task#8

Remove solutions from tasks 1-4. My fault!

**Comment by Daqueze21** [comment]
Update files

**Comment by FedorovD** [comment]
Closing the PR as accepted! Thanks!

**Pull request closed without merging**
