### PR TITLE
#5Task. Kirill Mikulich

### PR DESCRIPTION
**Pull request by KirillMikulich**
https://travis-ci.org/github/KirillMikulich/js-assignments/builds/714537781

### CODE REVIEW

**Comment by vramaniuk** [comment]
Please, put in your PR only changes for tasks that need to be in this branch

Selection_064
To prevent unnecessary changes being in this PR, when you are done with some task , you should checkout to initial state (master branch with no changes) and then create new branch "number_of_task"_task

Now you can discard changes in these unexpectable files using git command
`git checkout HEAD <file name>`,   `git checkout HEAD 01-string-tasks.js`   

I'll mark the PR as "Draft", please click "ready for review" when it will be finished. Thank you!

**Comment by KirillMikulich** [comment]
> Please, put in your PR only changes for tasks that need to be in this branch
> 
> Selection_064
> To prevent unnecessary changes being in this PR, when you are done with some task , you should checkout to initial state (master branch with no changes) and then create new branch "number_of_task"_task
> 
> Now you can discard changes in these unexpectable files using git command
> `git checkout HEAD <file name>`, `git checkout HEAD 01-string-tasks.js`
> 
> I'll mark the PR as "Draft", please click "ready for review" when it will be finished. Thank you!

do not quite understand

**Comment by vramaniuk** [comment]
Your PR is dirty. It contains  task1-4 solutions.
You shoud execute commands (in js-assignmens folder)
`git checkout HEAD 01-strings-tasks.js`
`git checkout HEAD 02-numbers-tasks.js`
`git checkout HEAD 03-date-tasks.js`
`git checkout HEAD 04-arrays-tasks.js`

and then commit 
It will revert changes in these files to initial state

**Comment by KirillMikulich** [comment]
Никогда такого не делал, мне необходимо вернуть эти 4 файла в ветке 5_tasks в исходное состояние?

**Comment by vramaniuk** [comment]
Closing the PR as accepted! Thanks!

**Pull request closed without merging**
