### PR TITLE
#5Task. Andrey Tereshkin

### PR DESCRIPTION
**Pull request by Terem**

### CODE REVIEW

**Comment by vramaniuk** [comment]
Please, privide the direct link to your task success travis build

Also files
Selection_051
shoudn't  be changed in this PR

Try to execute the command `git checkout HEAD 01-strings-tasks.js `  for all unwantedly modified files.

**Comment by vramaniuk** [comment]
I'll mark the PR as "Draft", please click "ready for review" when it will be finished. Thank you!

**Comment by Terem** [comment]
https://travis-ci.org/github/Terem/js-assignments/builds/726590079

**Comment by vramaniuk** [comment]
Closing the PR as accepted! Thanks!

**Pull request closed without merging**
