### PR TITLE
1-4Task. Lina

### PR DESCRIPTION
**Pull request by linais**
https://travis-ci.org/github/linais/js-assignments/builds/731426859

### CODE REVIEW

**Comment by vramaniuk** [comment]
Selection_016
This file shouldn't have been changed in this PR. 
You should create specific branch for every task.
task1_4 for tasks 1-4, task5 for task5 ...

**Comment by vramaniuk** [comment]
I'll mark the PR as "Draft", please click "ready for review" when it will be finished. Thank you!

**Comment by linais** [comment]
> I'll mark the PR as "Draft", please click "ready for review" when it will be finished. Thank you

> I'll mark the PR as "Draft", please click "ready for review" when it will be finished. Thank you!

Sorry, I pressed the 'draft' button by mistake. Could you mark PR as 'draft' again? Thanks.

**Comment by vramaniuk** [comment]
Please, create specific branch for this task (task1_4 for example)
You can use `git checkout -b task1_4` command

**Comment by vramaniuk** [comment]
I'll mark the PR as "Draft", please click "ready for review" when it will be finished. Thank you!

**Comment by linais** [comment]
Created another PR

**Pull request closed without merging**
