### PR TITLE
#7Task. Ira S-H

### PR DESCRIPTION
**Pull request by irmir**
https://travis-ci.org/github/irmir/js-assignments

### CODE REVIEW

**Comment by vramaniuk** [comment]
> https://travis-ci.org/github/irmir/js-assignments

Please, privide the direct link to your task success travis build

**Comment by vramaniuk** [comment]
I'll mark the PR as "Draft", please click "ready for review" when it will be finished. Thank you!

**Comment by irmir** [comment]
Direct link to my task success travis build 
https://travis-ci.org/github/irmir/js-assignments/builds/710784874

**Comment by vramaniuk** [comment]
Closing the PR as accepted! Thanks!

**Pull request closed without merging**
