### PR TITLE
#Task 9 Yury.Lagodich

### PR DESCRIPTION
**Pull request by zym43210**
https://travis-ci.com/github/zym43210/js-assignments/builds/174237653

### CODE REVIEW

**Comment by IlyaMokin** [comment]
Loos quite good, but a few notes which should be completed before...
 - **most important thing**: each of the next tasks includes previous changes. The main idea is to spit tasks by branch for simple review. In you case all changes in all PRs. Please split the tasks by relevant branches.
 - the PR has redundant changes in styling, spaces, comments....
  Please follow the simple rules:
   - do not add any non logic changes to code if review is required
   - if the changes in styling are important - you can do it as separate PR with styling only changes to avoid noise in the main PR


I'll mark your PRs as "Draft", please click "ready for review" when these will be finished.
Thank you for your efforts!

**Comment by zym43210** [comment]
Do i understand correctly, you admitted all 1-9 tasks?

**Comment by IlyaMokin** [comment]
no, only the 1st

**Comment by zym43210** [comment]
repaired

**Pull request closed without merging**
