### PR TITLE
5 Task Dmitry Gaiduk

### PR DESCRIPTION
**Pull request by IdokkeI**

### CODE REVIEW

**Comment by vramaniuk** [comment]
Please, put in your PR only changes for tasks that need to be in this branch

Selection_001

Revert commit 278d545

To prevent unnecessary changes being in this PR, when you are done with some task , you should checkout to initial state (master branch with no changes) and then create new branch "number_of_task"_task

**Comment by vramaniuk** [comment]
Please, privide the direct link to your task success travis build

**Comment by vramaniuk** [comment]
I'll mark the PR as "Draft", please click "ready for review" when it will be finished. Thank you!

**Comment by IdokkeI** [comment]
link to new PR: https://github.com/AisBrestEDU/js-assignments/pull/951,
link to travis: https://travis-ci.com/github/IdokkeI/js-assignments/builds/181790651

**Comment by vramaniuk** [comment]
It's duplicat. I'm closing it

**Pull request closed without merging**
