### PR TITLE
#Task5 andrei.meshkov

### PR DESCRIPTION
**Pull request by AndreyMeshkov**
https://travis-ci.com/github/AndreyMeshkov/js-assignments

### CODE REVIEW

**Comment by AlexMokin** [comment]
each pull reqeust has to have only changes for a given task. The 5th task in this case.

I'll mark the PR as "Draft", please click "ready for review" when it will be finished. Thank you!

**Comment by AlexMokin** [comment]
changes must be only in files related to the task. Also keep formatting of the original code

I'll mark the PR as "Draft", please click "ready for review" when it will be finished. Thank you!

**Comment by AlexMokin** [comment]
There are still changes in files not related to the task. Also you must keep formatting for the original code. Check other requests as well

image

Please do not re-open the request until fixed

I'll mark the PR as "Draft", please click "ready for review" when it will be finished. Thank you!

**Comment by AndreyMeshkov** [comment]
Revert the marked lines back to the original code. Before that, there was auto-formatting of the code when saving was enabled. Should this be done this way? Because I disabled auto-formatting, and copied the marked lines from Ilya's repository.

**Comment by AlexMokin** [comment]
Still see 9 modified files, see image below. I believe there were 5 files that needed to be modified for this task.

Make sure you fix this before re-openig

I'll mark the PR as "Draft", please click "ready for review" when it will be finished. Thank you!

image

**Comment by elizavetaShcherbatykhAis** [comment]
I saw your new PR. I close this one

**Pull request closed without merging**
