### PR TITLE
#5 Task. Gaziz_Tuleukulov

### PR DESCRIPTION
**Pull request by Gaziz666**
https://travis-ci.org/github/Gaziz666/js-assignments/builds/707334682

### CODE REVIEW

**Comment by Gaziz666** [comment]
https://travis-ci.org/github/Gaziz666/js-assignments/builds/705309190

**Comment by elizavetaShcherbatykhAis** [comment]
In your PR you need to put only files that related to the task (5 task in your situation).
 I'll mark the PR as draft please click "ready for review" when it will be corrected!
Thank you!

**Comment by Gaziz666** [comment]
hi i changed README file, and before  i reload 1-4 task. if it didn't correct, please will tel me, because i did it on other tasks (6-8)

**Comment by elizavetaShcherbatykhAis** [comment]
I see, I mean, files of tasks 1-4 mustn't have to be in this PR.
I close your PR now as accepted, because everything is well done :)
But next time, please be more attentive and put in your PR only files for the needed task.
Thank you!

**Pull request closed without merging**
