### PR TITLE
#5 task.andrei.manya

### PR DESCRIPTION
**Pull request by AndreiManya**

### CODE REVIEW

**Comment by AlexMokin** [comment]
pr must have changes in files related only to the given task.

I'll mark the PR as "Draft", please click "ready for review" when it will be finished. Thank you!

**Comment by AlexMokin** [comment]
in this pull request there shouldn't be any changes to loop-n-condtiions task. See image below 

image

I'll mark the PR as "Draft", please click "ready for review" when it will be finished. Thank you!

**Comment by AlexMokin** [comment]
also please provide a line to test in travis

**Comment by AndreiManya** [comment]
https://travis-ci.org/github/AndreiManya/js-assignments/builds/709426060

**Comment by AlexMokin** [comment]
in this pull request there shouldn't be any changes to loop-n-condtiions task. See image below 

image

I'll mark the PR as "Draft", please click "ready for review" when it will be finished. Thank you!

**Comment by AndreiManya** [comment]
https://travis-ci.org/github/AndreiManya/js-assignments/builds/710436048

**Comment by AlexMokin** [comment]
accepted

**Pull request closed without merging**
