### PR TITLE
Task1-4

### PR DESCRIPTION
**Pull request by Sergey-Starushkin**

### CODE REVIEW

**Comment by KostyaKov** [comment]
Hello, can you add Travis link to description, please?

**Comment by Sergey-Starushkin** [comment]
https://travis-ci.org/github/Sergey-Starushkin/js-assignments/builds/723808767

**Comment by KostyaKov** [comment]
Also, PR has a lot of redundant changes (File changed 20).
Can you update PR with changes related to task 1-4, please?

**Comment by Sergey-Starushkin** [comment]
a lot of files have been changed since when I copied the draft, these files were not yet there. or would you like me to update the project to the latest version of your project?

**Pull request closed without merging**
